os: windows

language: cpp

compiler:
- mingw

before_script:
- mkdir build
- cd build
- cmake -DCMAKE_BUILD_TYPE=Release ..
- cmake --build . --verbose

script: make

after_success:
# set up our cfg
- git config --global user.email "travis@travis-ci.com"
- git config --global user.name "Travis CI"
# copy our just built file to the releases folder
- cp ./TFTrue.so ../release/TFTrue.so -vf
# checkout our current branch, so we're not on a detatched head
- git checkout ${TRAVIS_BRANCH}
# add our built file
- git add ../release/TFTrue.so
# commit, add correct remote, and push
- git commit --message "Travis build ${TRAVIS_BUILD_NUMBER} on branch ${TRAVIS_BRANCH}"
- git remote add origin-push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
- git push -u origin-push ${TRAVIS_BRANCH}

# GH_TOKEN is a secret token defined in your travis proj

