os: linux

dist: bionic

language: cpp

compiler:
- gcc

addons:
  apt:
    packages:
    - qt5-default
    - g++-11-multilib
    - gcc-11-multilib
    - linux-libc-dev:i386
    sources:
    - sourceline: ppa:ubuntu-toolchain-r/test

install:
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 20
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 20
before_script:
- mkdir build
- cd build
- qmake ../TFTrue.pro -r -spec linux-g++ #-qt=qt5

script: make

after_success:
# set up our cfg
- git config --global user.email "travis@travis-ci.com"
- git config --global user.name "Travis CI"
# copy our just built file to the releases folder
- cp ./TFTrue.so ../release/TFTrue.so -vf
# checkout our current branch, so we're not on a detatched head
- git checkout ${TRAVIS_BRANCH}
# add our built file
- git add ../release/TFTrue.so
# commit, add correct remote, and push
- git commit --message "Travis build ${TRAVIS_BUILD_NUMBER} on branch ${TRAVIS_BRANCH}"
- git remote add origin-push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
- git push -u origin-push ${TRAVIS_BRANCH}

# GH_TOKEN is a secret token defined in your travis proj

